// Role constants matching backend
export const ROLE_SUPER = 'super'
export const ROLE_ADMIN = 'admin'
export const ROLE_USER = 'user'

export const staticRoutes = [
  {
    name: 'dashboard',
    path: '/dashboard',
    title: 'Dashboard',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    pinTab: true,
    menuType: 'page',
    componentPath: '/dashboard/index.vue',
    id: 1,
    pid: null,
    // Available to all roles
  },
  {
    name: 'userCenter',
    path: '/user-center',
    title: 'Personal Center',
    requiresAuth: true,
    icon: 'icon-park-outline:user',
    menuType: 'page',
    hide: true,
    componentPath: '/user-center/index.vue',
    id: 10,
    pid: null,
    // Available to all roles; reached via the header avatar dropdown
  },
  {
    name: 'nextflow',
    path: '/nextflow',
    title: 'Nextflow',
    requiresAuth: true,
    icon: 'local:nextflow-icon-dark',
    menuType: 'dir',
    componentPath: null,
    id: 3,
    pid: null,
    // Available to all roles
  },
  {
    name: 'pipeLine',
    path: '/nextflow/pipeline',
    title: 'Pipelines',
    requiresAuth: true,
    icon: 'carbon:pipelines',
    componentPath: '/application/nextflow/pipeline/index.vue',
    id: 301,
    pid: 3,
    // Available to all roles
  },
  {
    name: 'nextflow-job',
    path: '/nextflow/job',
    title: 'Jobs',
    requiresAuth: true,
    icon: 'carbon:batch-job',
    componentPath: '/application/nextflow/job/index.vue',
    id: 302,
    pid: 3,
    // Available to all roles
  },
  {
    name: 'nextflow-launch',
    path: '/nextflow/launch',
    title: 'Launch',
    requiresAuth: true,
    icon: 'carbon:launch',
    componentPath: '/application/nextflow/launch/index.vue',
    id: 303,
    pid: 3,
    // Available to all roles
  },
  {
    name: 'nextflow-launch-configuration',
    path: '/nextflow/launch/configuration',
    title: 'Configure launch',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    hide: true,
    menuType: 'page',
    componentPath: '/application/nextflow/launch/configuration/index.vue',
    id: 304,
    pid: 3,
    // Available to all roles
  },
  {
    name: 'storage',
    path: '/storage',
    title: 'Storage',
    requiresAuth: true,
    icon: 'icon-park-outline:storage-card-two',
    menuType: 'dir',
    componentPath: null,
    id: 4,
    pid: null,
    // Available to all roles
  },
  {
    name: 'minio',
    path: '/storage/minio',
    title: 'MinIO',
    requiresAuth: true,
    icon: 'icon-park-outline:cloud-storage',
    componentPath: '/application/storage/minio/index.vue',
    id: 401,
    pid: 4,
    // Available to all roles
  },
  {
    name: 'automapper',
    path: '/automapper',
    title: 'AutoMapper',
    requiresAuth: true,
    icon: 'carbon:software-resource-cluster',
    componentPath: '/application/automapper/index.vue',
    id: 5,
    pid: null,
    // Available to all roles
  },
  {
    name: 'ai-chat',
    path: '/ai-chat',
    title: 'AI Chat',
    requiresAuth: true,
    icon: 'icon-park-outline:robot',
    menuType: 'page',
    componentPath: '/ai/chat/index.vue',
    id: 9,
    pid: null,
    // Available to all roles
  },
  {
    name: 'userSetting',
    path: '/user-setting',
    title: 'User Settings',
    requiresAuth: true,
    icon: 'icon-park-outline:config',
    menuType: 'dir',
    componentPath: null,
    id: 7,
    pid: null,
    // Available to all roles
  },
  {
    name: 'storageSetting',
    path: '/user-setting/storage',
    title: 'Storage',
    requiresAuth: true,
    icon: 'icon-park-outline:cloud-storage',
    componentPath: '/setting/storage/index.vue',
    id: 701,
    pid: 7,
    // Available to all roles
  },
  {
    name: 'llmSetting',
    path: '/user-setting/llm',
    title: 'LLM',
    requiresAuth: true,
    icon: 'icon-park-outline:robot',
    componentPath: '/setting/llm/index.vue',
    id: 702,
    pid: 7,
    // Available to all roles
  },
  {
    name: 'agentWorkspaceSetting',
    path: '/user-setting/agent-workspace',
    title: 'Agent Workspace',
    requiresAuth: true,
    icon: 'icon-park-outline:folder-success',
    componentPath: '/setting/agent-workspace/index.vue',
    id: 703,
    pid: 7,
  },
  {
    name: 'mcpSetting',
    path: '/user-setting/mcp',
    title: 'MCP Servers',
    requiresAuth: true,
    icon: 'icon-park-outline:connection-point',
    componentPath: '/setting/mcp/index.vue',
    id: 704,
    pid: 7,
  },
  {
    name: 'skillsSetting',
    path: '/user-setting/skills',
    title: 'Agent Skills',
    requiresAuth: true,
    icon: 'icon-park-outline:bookmark',
    componentPath: '/setting/skills/index.vue',
    id: 705,
    pid: 7,
  },
  {
    name: 'apiKeySetting',
    path: '/user-setting/api-keys',
    title: 'API Keys',
    requiresAuth: true,
    icon: 'icon-park-outline:key',
    componentPath: '/setting/api-keys/index.vue',
    id: 706,
    pid: 7,
  },
  {
    name: 'setting',
    path: '/setting',
    title: 'System Settings',
    requiresAuth: true,
    icon: 'icon-park-outline:setting',
    menuType: 'dir',
    componentPath: null,
    id: 6,
    pid: null,
    // Super only
    roles: [ROLE_SUPER],
  },
  {
    name: 'accountSetting',
    path: '/setting/account',
    title: 'User Management',
    requiresAuth: true,
    icon: 'icon-park-outline:every-user',
    componentPath: '/setting/account/index.vue',
    id: 601,
    pid: 6,
    // Super only
    roles: [ROLE_SUPER],
  },
  {
    name: 'menuSetting',
    path: '/setting/menu',
    title: 'Menu Settings',
    requiresAuth: true,
    icon: 'icon-park-outline:application-menu',
    componentPath: '/setting/menu/index.vue',
    id: 602,
    pid: 6,
    // Super only
    roles: [ROLE_SUPER],
  },
  {
    name: 'authSetting',
    path: '/setting/auth',
    title: 'Auth Providers',
    requiresAuth: true,
    icon: 'icon-park-outline:shield-add',
    componentPath: '/setting/auth/index.vue',
    id: 603,
    pid: 6,
    // Super only
    roles: [ROLE_SUPER],
  },
  {
    name: 'groupSetting',
    path: '/setting/group',
    title: 'Groups & Storage',
    requiresAuth: true,
    icon: 'icon-park-outline:peoples',
    componentPath: '/setting/group/index.vue',
    id: 604,
    pid: 6,
    // Super only: granting storage to a group decides who can read controlled
    // data, which is the separation-of-duties boundary for this feature.
    roles: [ROLE_SUPER],
  },
]
